version: "3.8"

services:
  php:
    container_name: slim_php
    build: ./
    ports:
      - 8080:8080
    volumes:
      - ./:/var/www/slim_app
      - /var/www/slim_app/vendor
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - 3306:3306
    volumes:
      - ./DB/MYSQL:/var/lib/mysql
