version: "3.8"

services:
  php:
    container_name: slim_php
    build: ./
    ports:
      - 8086:8086
    volumes:
      - ./:/var/www/slim_app
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: example

  adminer:
    image: adminer
    ports:
      - 8080:8080